### PR TITLE
Add onclick play/pause functionality to clips #14

### PR DESCRIPTION
**Pull request by jbccollins**
- One line change. Pretty self explanatory.

### CODE REVIEW

**Comment by jbccollins** [comment]
Hmm. Ok I'm unfamiliar with how github links issues across forks so that "#14 #15" thing looks a bit weird. 

I was not able to reproduce any sort of play button appearing intermittently. Nothing obvious in the html and I checked the css but didn't see and classes that seemed relevant so @chrisfried if you have some suggestion as to where I might find such a button then please let me know. For now this PR just allows you to click the video to play/pause without any sort of button overlay.

**Comment by chrisfried** [comment]
The play button is supposed to be coming from Video.js. I'm not sure Video.js is actually doing anything, at this point...

I like this fix, but could you use Angular's `(click)` rather than `onclick`, for consistincy?

**Comment by jbccollins** [comment]
@chrisfried Yeah sure I can do that. Updated.

**Comment by chrisfried** [comment]
Merged! What's your Gamertag? I'll tag you as a contributor if you like.

**Comment by jbccollins** [comment]
Cool! My Gamertag is "My Derpy Turtle".

**Pull request merged**
